baseURL = "http://example.org/"
languageCode = "en-us"
title = "Red Team \n DevOps Project"
theme = "m10c"

[params]
  description = "This is the Project 1 page for Red Team, developed by the Red Dev Team and deployed by the Red Ops Team!"

[author]
  name = "reddev"
  profilepic = "/img/download.png"
[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"

[taxonomies]
  tag = "tags"

